org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false

# Du an nam o o D:, thu vien Flutter nam o o C: -> Kotlin bien dich tang dan bi loi "different roots".
# Tat bien dich tang dan cua Kotlin de tranh loi nay.
kotlin.incremental=false
